//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnGrandesExposiciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campos()
        {
            this.Valor_Campos = new HashSet<Valor_Campos>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_TABLA { get; set; }
        public Nullable<int> ID_FORMULA { get; set; }
        public string CAMPO { get; set; }
        public Nullable<int> ORDEN_HORIZONTAL { get; set; }
        public string ALIAS { get; set; }
    
        public virtual Formulas Formulas { get; set; }
        public virtual Tablas Tablas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valor_Campos> Valor_Campos { get; set; }
    }
}
