//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnGrandesExposiciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exposiciones
    {
        public int ID { get; set; }
        public int ID_PERIODO { get; set; }
        public System.DateTime FECHA_ALTA { get; set; }
        public System.DateTime FECHA_MOD { get; set; }
        public string LEGAJO { get; set; }
        public bool VALIDADO { get; set; }
    
        public virtual Periodos Periodos { get; set; }
    }
}
