//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnGrandesExposiciones.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GrandesExposicionesEntities : DbContext
    {
        public GrandesExposicionesEntities()
            : base("name=GrandesExposicionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Formulas> Formulas { get; set; }
        public virtual DbSet<Tablas> Tablas { get; set; }
        public virtual DbSet<Valor_Campos> Valor_Campos { get; set; }
        public virtual DbSet<Campos> Campos { get; set; }
        public virtual DbSet<Archivos_Exposiciones> Archivos_Exposiciones { get; set; }
        public virtual DbSet<Exposiciones> Exposiciones { get; set; }
        public virtual DbSet<Periodos> Periodos { get; set; }
        public virtual DbSet<Parametros_Exposiciones> Parametros_Exposiciones { get; set; }
    }
}
