//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnGrandesExposiciones.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Parametros_Exposiciones
    {
        public int ID { get; set; }
        public int ID_PERIODO { get; set; }
        public double TIER_1 { get; set; }
        public double TIER_2 { get; set; }
        public double TIER_3 { get; set; }
        public double SMVM { get; set; }

        [DisplayName("Periodo")]
        public virtual Periodos Periodos { get; set; }
    }
}
